### PR TITLE
Added stuffs for ItemMaker

### PR DESCRIPTION
**Pull request by sirLimbs**
bleh

### CODE REVIEW

**Comment by iw2d** [comment]
There's no actual packet handling / sending? 🤔

**Comment by sirLimbs** [comment]
> There's no actual packet handling / sending? 🤔

Yup, I think this was it, just need to call the ItemMaker method

**Comment by iw2d** [comment]
I did end up just rewriting everything to keep with the coding style and to implement incorrect / missing stuff https://github.com/iw2d/kinoko/commit/53f8e9572dfbbac65206011109b82f2d889073f5
Thanks for the PR though

**Comment by sirLimbs** [comment]
> keep 

Dope, code looks great.

**Pull request closed without merging**
